create table if not exists public.vocabulary (
  id bigint generated by default as identity primary key,
  word text not null unique,
  pos text not null,
  meaning text not null,
  main_meaning text not null,
  meanings jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.vocabulary add column if not exists pos text;
alter table public.vocabulary add column if not exists meaning text;
alter table public.vocabulary add column if not exists main_meaning text;
alter table public.vocabulary add column if not exists meanings jsonb not null default '[]'::jsonb;
alter table public.vocabulary add column if not exists created_at timestamptz not null default timezone('utc', now());

update public.vocabulary
set pos = coalesce(pos, 'unknown'),
    meaning = coalesce(meaning, main_meaning),
    main_meaning = coalesce(main_meaning, meaning),
    meanings = case
      when jsonb_array_length(coalesce(meanings, '[]'::jsonb)) = 0
        then jsonb_build_array(coalesce(main_meaning, meaning))
      else meanings
    end
where pos is null
   or meaning is null
   or main_meaning is null
   or meanings is null;

alter table public.vocabulary alter column pos set not null;
alter table public.vocabulary alter column meaning set not null;
alter table public.vocabulary alter column main_meaning set not null;

alter table public.vocabulary enable row level security;

drop policy if exists "anon_select_vocabulary" on public.vocabulary;
create policy "anon_select_vocabulary"
on public.vocabulary
for select
to anon
using (true);

drop policy if exists "anon_insert_vocabulary" on public.vocabulary;
create policy "anon_insert_vocabulary"
on public.vocabulary
for insert
to anon
with check (true);

drop policy if exists "anon_update_vocabulary" on public.vocabulary;
create policy "anon_update_vocabulary"
on public.vocabulary
for update
to anon
using (true)
with check (true);

drop policy if exists "anon_delete_vocabulary" on public.vocabulary;
create policy "anon_delete_vocabulary"
on public.vocabulary
for delete
to anon
using (true);
