-- ============================================================
-- Vocabulary Learning System — Full Schema
-- ============================================================

-- Clear existing data (schema migration for auth)
delete from public.study_log;
delete from public.user_stats;
delete from public.vocabulary;

-- 1. VOCABULARY (extend with user_id + spaced repetition fields)
-- Add column as nullable first (existing rows have no user_id)
alter table if exists public.vocabulary
  add column if not exists user_id uuid references auth.users default auth.uid(),
  add column if not exists source text,
  add column if not exists ease_factor float not null default 2.5,
  add column if not exists review_interval_days int not null default 1,
  add column if not exists next_review_date timestamptz not null default timezone('utc', now());

-- Delete rows that still have null user_id (pre-migration data, owner unknown)
delete from public.vocabulary where user_id is null;

-- Now safe to set NOT NULL
alter table public.vocabulary alter column user_id set not null;

-- Drop old unique constraint on word, add composite unique (user_id, word)
alter table public.vocabulary drop constraint if exists vocabulary_word_key;
alter table public.vocabulary add constraint vocabulary_user_word_unique unique (user_id, word);

-- 2. STUDY_LOG
create table if not exists public.study_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  word_id bigint not null references public.vocabulary(id) on delete cascade,
  action text not null check (action in ('review', 'remembered', 'quiz_correct', 'quiz_wrong')),
  difficulty text check (difficulty in ('easy', 'medium', 'hard')),
  reviewed_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_study_log_user_word_time
  on public.study_log (user_id, word_id, reviewed_at desc);

-- 3. USER_STATS
create table if not exists public.user_stats (
  user_id uuid primary key references auth.users(id) on delete cascade,
  total_words int not null default 0,
  remembered_words int not null default 0,
  current_streak int not null default 0,
  longest_streak int not null default 0,
  last_review_date date,
  total_reviews int not null default 0,
  updated_at timestamptz not null default timezone('utc', now())
);

-- 4. RLS — enable & drop old policies
alter table public.vocabulary enable row level security;
alter table public.study_log enable row level security;
alter table public.user_stats enable row level security;

-- Drop old anon policies
drop policy if exists "anon_select_vocabulary" on public.vocabulary;
drop policy if exists "anon_insert_vocabulary" on public.vocabulary;
drop policy if exists "anon_update_vocabulary" on public.vocabulary;
drop policy if exists "anon_delete_vocabulary" on public.vocabulary;

-- New RLS: user-scoped
create policy "user_manage_own_vocabulary"
  on public.vocabulary
  for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "user_manage_own_study_log"
  on public.study_log
  for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "user_manage_own_stats"
  on public.user_stats
  for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());
